### ISSUE TITLE
Gradle support?

### ISSUE THREAD

**Issue by c-p-b** [timvw/generator-scala#6]
I noticed Maven and SBT are supported, might be nice to get a gradle scaffolder as well.

**Comment by timvw** [comment]
Agreed. Currently looking into the composability features to allow for better (sub) generators targetting more build systems (and/or) dependencies

**Comment by timvw** [comment]
Functionality is now available ;)

yo scala gradle <appname> <scalaversion>

**Comment by c-p-b** [comment]
Thanks! I'll give this a whirl. 🍺
